# Generated by Django 4.2.5 on 2023-09-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/"),
        ),
    ]
