# Generated by Django 4.2.5 on 2023-09-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0002_servicetype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
