# Generated by Django 4.2.5 on 2023-09-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0004_alter_servicetype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                auto_created=True,
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
