# Generated by Django 4.2.5 on 2023-09-15 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0008_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="NewsPost",
        ),
    ]
