# Generated by Django 4.2.5 on 2023-09-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0009_rename_post_newspost"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
