# Generated by Django 4.2.5 on 2023-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0010_newspost_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
