# Generated by Django 4.2.5 on 2023-11-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0011_newspost_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/banner/")),
                ("link", models.URLField()),
                ("interval_seconds", models.PositiveIntegerField(default=3000)),
            ],
        ),
    ]
