# Generated by Django 4.2.5 on 2023-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0014_voucher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucher",
            old_name="description",
            new_name="title",
        ),
    ]
